### ISSUE TITLE
I'd Rather Be Playing Video Games React

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#100]
## Objective

Reimplement the video games search app using `React.useState` and `React.useEffect`

## Instructions

- Fork the repl at https://replit.com/@andyweiss1982/RatherBePlayingVideoGamesReact
- There are detailed instructions in `src/App.jsx`
- use https://replit.com/@andyweiss1982/RatherWatchMoviesReact#src/App.jsx as a rough guide

## Submission Guidelines

Paste a link to your forked repl as a comment to this issue at 10 AM EST

**Comment by vlopesdacosta** [comment]
https://replit.com/join/ihpwortftk-vlopesdacosta

**Comment by Latte-King** [comment]
https://replit.com/join/fshktzndoi-rhamid2
