### ISSUE TITLE
React Review

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#103]
# Objective

Make a "simple" React website that displays the name and image of the new BK Ch'king sandwich from sanity, a la: https://chking.andyweiss1982.repl.co/

## Designs

![Screen Shot 2021-06-28 at 7 59 17 AM](https://user-images.githubusercontent.com/8116130/123633081-bf7ca900-d7e6-11eb-9053-1c9135f5816c.png)

## Dev Notes

1. Make a new React.js repl and delete the CSS in `src/App.css`
2. Inside of `src/App.jsx`, declare a React state variable called `chking`, which defaults to an empty object.
3. Declare a function that makes a JSON POST request to the BK sanity url (https://czqk28jt.apicdn.sanity.io/v1/graphql/prod_bk_us/default), and passes in a query that will request the english name of the sandwich, and its image asset url.  HINT: the Ch'king is an "Item" in sanity with an id of "edfb52db-081b-45bf-a33b-4b21d0885ef8".  Await the parsing of the JSON response, and `setChking` to equal the resulting data's "Item" property.
4. Call `useEffect` to make sure this function runs once, when the page loads.
5. Return a main tag with an img and an h1 inside.
6. The `Flame-Bold` font lives at https://www.bk.com/assets/bk/Flame-Bold.woff.  Create a `fonts` folder in `src` and add it there.
7. Inside of `src/App.css`, declare the `Flame-Bold` font face, as well as `mayo` and `brown` CSS variables.
8. Add CSS as desired to display the h1 and image in `src/App.jsx` with BK branding.

## Submission Guidelines

Paste a link to your repl as a comment to this issue at 10 AM EST

**Comment by vlopesdacosta** [comment]
https://replit.com/join/agcqhecsos-vlopesdacosta

**Comment by Latte-King** [comment]
https://replit.com/join/mvtmxckjfb-rhamid2
