### ISSUE TITLE
Weather Dot Com

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#52]
# Objective

Make a website that shows a 10 day weather forecast for your favorite city.

If you like, you can use one of these as a guide: 

* https://weather.com/weather/tenday/l/a046396ee1fec5cda57bcb108802d744193aaf1826d24362b54fd32d5f2393ec
* https://ca.news.yahoo.com/weather/portugal/lisbon/lisbon-742676

You can try to match the look and feel of an existing site, or you can give your site your own personal touch of style.

You may want to consider using either an html table, or css grid to layout your content.  Focus on nicely displaying the actual forecast before moving on to other elements like navigation or ads -- only if you have time.  Don't worry on adding any interactivity to your site, this is just an HTML / CSS exercise (for now 🤔)

If you want, you can use the weather icons below.  You can also find free images at unsplash.com.

## Reference

https://www.w3schools.com/html/html_tables.asp

https://www.w3schools.com/css/css_grid.asp

## Submission guidelines

Initialize a new repository, commit your work, push it to Github, and enable GitHub pages.

As a comment to this issue, submit urls to _both_ your resume HW _and_ your work for this exercise.

--- 

Images:

Right click any image you want to save it to your project folder.  Use it in your work with an `img` tag.

![a01d](https://user-images.githubusercontent.com/8116130/106545690-ee148300-64d7-11eb-8095-bad746a8c7ae.png)
![a01n](https://user-images.githubusercontent.com/8116130/106545691-eead1980-64d7-11eb-8fb2-27c7e52a0095.png)
![c01d](https://user-images.githubusercontent.com/8116130/106545704-f076dd00-64d7-11eb-9435-6313f5b42e48.png)
![c01n](https://user-images.githubusercontent.com/8116130/106545705-f076dd00-64d7-11eb-93d9-fafb00fdec27.png)
![c02d](https://user-images.githubusercontent.com/8116130/106545707-f076dd00-64d7-11eb-9e40-d083f7295743.png)
![c02n](https://user-images.githubusercontent.com/8116130/106545709-f076dd00-64d7-11eb-9bb9-b15b1dc03c4b.png)
![c03d](https://user-images.githubusercontent.com/8116130/106545712-f10f7380-64d7-11eb-92da-e91e5a026d78.png)
![c03n](https://user-images.githubusercontent.com/8116130/106545713-f10f7380-64d7-11eb-8b58-5db7bc6bf328.png)
![c04d](https://user-images.githubusercontent.com/8116130/106545715-f10f7380-64d7-11eb-8bc3-d50cc99034f5.png)
![c04n](https://user-images.githubusercontent.com/8116130/106545717-f10f7380-64d7-11eb-960c-f1a0759f005c.png)
![d01d](https://user-images.githubusercontent.com/8116130/106545718-f1a80a00-64d7-11eb-9e60-d5dc606be826.png)
![d01n](https://user-images.githubusercontent.com/8116130/106545719-f1a80a00-64d7-11eb-8533-6513064fa7a7.png)
![d02d](https://user-images.githubusercontent.com/8116130/106545720-f1a80a00-64d7-11eb-9f35-adf174ef10a4.png)
![d02n](https://user-images.githubusercontent.com/8116130/106545721-f240a080-64d7-11eb-9b7b-2e9b10b207c2.png)
![d03d](https://user-images.githubusercontent.com/8116130/106545722-f240a080-64d7-11eb-9abc-a887f360a145.png)
![d03n](https://user-images.githubusercontent.com/8116130/106545723-f240a080-64d7-11eb-8eec-66a058cb15ad.png)
![f01d](https://user-images.githubusercontent.com/8116130/106545724-f240a080-64d7-11eb-997b-be13b6c19447.png)
![f01n](https://user-images.githubusercontent.com/8116130/106545725-f240a080-64d7-11eb-8f03-8b0de3333dc5.png)
![r01d](https://user-images.githubusercontent.com/8116130/106545726-f240a080-64d7-11eb-8358-b58da12ba6c8.png)
![r01n](https://user-images.githubusercontent.com/8116130/106545727-f2d93700-64d7-11eb-9a54-a22f014fea57.png)
![r02d](https://user-images.githubusercontent.com/8116130/106545728-f2d93700-64d7-11eb-87aa-c50703dd63fb.png)
![r02n](https://user-images.githubusercontent.com/8116130/106545730-f2d93700-64d7-11eb-8213-b8fc61f3da14.png)
![r03d](https://user-images.githubusercontent.com/8116130/106545731-f2d93700-64d7-11eb-8f74-4d17e0cb5d66.png)
![r03n](https://user-images.githubusercontent.com/8116130/106545733-f2d93700-64d7-11eb-824a-f7b99afd9382.png)
![r04d](https://user-images.githubusercontent.com/8116130/106545734-f2d93700-64d7-11eb-8ecf-3c00ce5d4b52.png)
![r04n](https://user-images.githubusercontent.com/8116130/106545736-f371cd80-64d7-11eb-8d81-a4b558a3753f.png)
![r05d](https://user-images.githubusercontent.com/8116130/106545737-f371cd80-64d7-11eb-9d1f-46afe97f9664.png)
![r05n](https://user-images.githubusercontent.com/8116130/106545738-f371cd80-64d7-11eb-8a29-d711a174275d.png)
![r06d](https://user-images.githubusercontent.com/8116130/106545739-f371cd80-64d7-11eb-8a0e-2049127fc3c0.png)
![r06n](https://user-images.githubusercontent.com/8116130/106545740-f371cd80-64d7-11eb-9258-c165d6e6878a.png)
![s01d](https://user-images.githubusercontent.com/8116130/106545741-f371cd80-64d7-11eb-9189-d80d28a9530f.png)
![s01n](https://user-images.githubusercontent.com/8116130/106545742-f40a6400-64d7-11eb-9cca-488288eccdea.png)
![s02d](https://user-images.githubusercontent.com/8116130/106545743-f40a6400-64d7-11eb-9046-b8e128a51ff2.png)
![s02n](https://user-images.githubusercontent.com/8116130/106545744-f40a6400-64d7-11eb-8528-7a767f71602d.png)
![s03d](https://user-images.githubusercontent.com/8116130/106545745-f40a6400-64d7-11eb-9343-6cd147de53e5.png)
![s03n](https://user-images.githubusercontent.com/8116130/106545746-f40a6400-64d7-11eb-91c8-d55ebd711506.png)
![s04d](https://user-images.githubusercontent.com/8116130/106545747-f40a6400-64d7-11eb-9a7c-d6dcb7b5dc58.png)
![s04n](https://user-images.githubusercontent.com/8116130/106545748-f4a2fa80-64d7-11eb-8e57-4c87b22e8424.png)
![s05d](https://user-images.githubusercontent.com/8116130/106545750-f4a2fa80-64d7-11eb-904b-4f6e639970e2.png)
![s05n](https://user-images.githubusercontent.com/8116130/106545751-f4a2fa80-64d7-11eb-88fa-cf432863dfe2.png)
![s06d](https://user-images.githubusercontent.com/8116130/106545752-f4a2fa80-64d7-11eb-86dd-bf8ebb52ce8e.png)
![s06n](https://user-images.githubusercontent.com/8116130/106545753-f4a2fa80-64d7-11eb-83dd-f59ec998a4de.png)
![t01d](https://user-images.githubusercontent.com/8116130/106545754-f53b9100-64d7-11eb-8af9-286b21646953.png)
![t01n](https://user-images.githubusercontent.com/8116130/106545756-f53b9100-64d7-11eb-81e5-8fd9cd6653c3.png)
![t02d](https://user-images.githubusercontent.com/8116130/106545757-f53b9100-64d7-11eb-81ee-6be1142fe32a.png)
![t02n](https://user-images.githubusercontent.com/8116130/106545759-f53b9100-64d7-11eb-8c11-0eab2bc96a2a.png)
![t03d](https://user-images.githubusercontent.com/8116130/106545760-f53b9100-64d7-11eb-9095-becdef06cfbd.png)
![t03n](https://user-images.githubusercontent.com/8116130/106545761-f53b9100-64d7-11eb-9c81-72d835e5d2bf.png)
![t04d](https://user-images.githubusercontent.com/8116130/106545762-f5d42780-64d7-11eb-8a91-ce800beffaf3.png)
![t04n](https://user-images.githubusercontent.com/8116130/106545763-f5d42780-64d7-11eb-877a-eeb55302bc17.png)
![t05d](https://user-images.githubusercontent.com/8116130/106545765-f5d42780-64d7-11eb-8ea3-8f523dd40470.png)
![t05n](https://user-images.githubusercontent.com/8116130/106545766-f5d42780-64d7-11eb-92bb-7e049984af2f.png)
![u00d](https://user-images.githubusercontent.com/8116130/106545767-f5d42780-64d7-11eb-845a-ca9dd9454cad.png)
![u00n](https://user-images.githubusercontent.com/8116130/106545768-f66cbe00-64d7-11eb-9c51-427155f04b6f.png)

**Comment by ebugbey** [comment]
https://ebugbey.github.io/ctg-bootcamp-weather-forecast/

**Comment by ebugbey** [comment]
https://ebugbey.github.io/ctg-bootcamp-resume/

**Comment by lilygdu** [comment]
https://lilygdu.github.io/bootcamp-resume-lily/

https://lilygdu.github.io/bootcamp-weather/
