### ISSUE TITLE
Popeyes Static Menu

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#54]
# Objective

Our task today is to create a clone of the Popeye's static menu: https://www.popeyes.com/menu

![Screen Shot 2021-02-05 at 8 02 37 AM](https://user-images.githubusercontent.com/8116130/107037059-8df83800-6788-11eb-95ae-a11e932db5cb.png)

## Instructions

Like yesterday, we have set your up with a read-only starter repo, at: https://github.com/rbi-learning/popeyes_static_menu.  You can see more instructions at https://github.com/rbi-learning/popeyes_static_menu#directions

To clean things up a little bit, we stored all of the starter fonts and images in an `assets` folder.  You should still do your work in `index.html` and `styles.css`.

## Submission Guidelines

At 10 AM, submit a link to your own GitHub repository as a comment to this issue.

**Comment by lilygdu** [comment]
https://lilygdu.github.io/popeyes-menu/

**Comment by ebugbey** [comment]
https://github.com/ebugbey/plk-static-menu
