### ISSUE TITLE
Putting the Fun in Functions

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#55]
# Objective

Today's morning exercise is all about functions...

You can do it all online, there's no need to work inside a git repository this morning.

Go to the following url: https://repl.it/@andyweiss1982/puttingFunInFunctions.  There are a series of small challenges there for you.  

## Directions

I have started 7 empty JavaScript functions using different styles (more on this [here](https://www.codecademy.com/courses/introduction-to-javascript/lessons/functions/exercises/function-declaration) in case you haven't gotten this far in Codecademy yet).  

Your job is to implement the body of each function so that each one returns the expected result.  Just below each function, I log a few different inputs to each functions, and with examples that show what I expect would be returned in each scenario.   You can check your work against these expectations to see if you are on the right track.

## Working with Repl.it

Notice that once you start working, the url at the top of the screen will change.  This is the url I want you to ultimately submit.  

If it's helpful, you can go to the "shell" tab and type `node` to enter a JavaScript playground.  You can use this area to experiment with different approaches to each problem, for example:

![Screen Shot 2021-02-07 at 6 02 08 PM](https://user-images.githubusercontent.com/8116130/107162041-9b6f1700-696e-11eb-99c3-1cd7159edef3.png)

To exit this playground, you can type `command + D`.

## Submission Guidelines

At 10 AM, submit the link to _your_ work as a comment to this issue.

If you so desire, it's totally fine with me if you want to work together.

**Comment by lilygdu** [comment]
https://repl.it/@lilygdu/puttingFunInFunctions#index.js

**Comment by lilygdu** [comment]
https://repl.it/join/ynzsfesy-lilygdu
