### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#56]
# Objective

To help us make small talk about the weather across the border, your goal is to make a Celsius / Fahrenheit temperature converter.  

## Example

https://user-images.githubusercontent.com/8116130/107365200-78498200-6aaa-11eb-84e1-04b6590f5278.mov

## Requirements

**GIVEN** the user has F selected in a dropdown
**WHEN** she enters a number into the number field
**THEN** she should see how many degrees that number is in C

**GIVEN** the user has C selected in a dropdown
**WHEN** she enters a number into the number field
**THEN** she should see how many degrees that number is in F

**GIVEN** the user has F selected in the a dropdown
**WHEN** she changes the dropdown to C
**THEN** should see how many degrees that number is in F
**AND** the background should show an image representative of Canada

**GIVEN** the user has C selected in the a dropdown
**WHEN** she changes the dropdown to F
**THEN** should see how many degrees that number is in C
**AND** the background should show an image representative of the United States.

## Submission Guidelines

You can do your work in repl.it, feel free to form this bare bones starter repo: https://repl.it/@andyweiss1982/Temperature-Converter-Starter.  

You can find free images at https://unsplash.com/.  Feel free to have fun with the styling.

Submit your work as a comment to this issue.

**Comment by lilygdu** [comment]
https://repl.it/join/pmjroyqu-lilygdu

**Comment by ebugbey** [comment]
https://repl.it/join/ifldkocs-ebugbey
