### ISSUE TITLE
Joke Generator

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#57]
# Objective

Up until now we have been writing lots of text directly inside of our HTML.  But in reality, we write very little text in our HTML in our apps, because we get it from external sources and pipe it into the document via JavaScript.  This morning's activity is meant to familiarize you with this practice.

## Directions

Fork the repl at https://repl.it/@andyweiss1982/AwfulJokes.  Inside the `script.js` file, there is an array of jokes.   Add an event listener to the button, such that whenever a user clicks the button, you display a new _random_ joke from the array to the user inside the div with an id of `#joke`.  In other words:

**GIVEN** the user is on the page
**WHEN** they click the button
**THEN** they should see a random joke.

<img width="796" alt="Screen Shot 2021-02-10 at 7 52 34 AM" src="https://user-images.githubusercontent.com/8116130/107512513-f1151080-6b74-11eb-8278-91d3419e83ee.png">

You are totally encouraged to improve the look and feel of the site with additional HTML or CSS, but you should be able to implement the task by working inside `script.js` alone.

## Submission Guidelines

At 10 AM, paste the url to your repl as a comment to this issue

**Comment by ebugbey** [comment]
https://repl.it/@ebugbey/AwfulJokes#script.js

**Comment by lilygdu** [comment]
https://repl.it/join/wdhqyoje-lilygdu
