### ISSUE TITLE
I'd Rather Be Playing Video Games

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#58]
# Objective

Yesterday you learned to interact with your own static JSON APIs -- we call them static because they always return the same data, no matter what.  Today you will start to work with dynamic APIs, which will send you custom responses depending on what you request in your query string. 

We will use this video games API as an example: https://api.rawg.io/docs/

To explore how it works, visit each of the following URLS: 

https://api.rawg.io/api/games?search=Mario
https://api.rawg.io/api/games?search=Zelda
https://api.rawg.io/api/games?search=Final+Fantasy

...and notice that the `results` array that comes back is different in each case.  We will leverage this to see that the user wants to search for, and display them matching results from this API.

## Directions

You can use this repl as a starting point: https://repl.it/@andyweiss1982/IdRatherBePlayingVideoGames.

Fork it and try to match the following interaction:

https://user-images.githubusercontent.com/8116130/107639504-f2127480-6c3e-11eb-91ee-069ca7f9b032.mov

**GIVEN** the user has entered text into the search bar
**WHEN** they submit the form
**THEN** they should see matching results displayed as cards with an image and title of each game

There are more step by step instructions in the `script.js` file

## Submission guidelines

At 10 AM, paste the url of your forked repl as a comment to this issue

**Comment by ebugbey** [comment]
https://repl.it/join/vprpimah-ebugbey

**Comment by lilygdu** [comment]
https://repl.it/join/pkdqekzm-lilygdu
