### ISSUE TITLE
Jeopardy!

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#59]
# Objective

This morning's activity integrates the different things we've been working on all week:

- forms
- fetching from APIs
- manipulating the DOM

Your goal is to build a reasonable approximation of the game Jeopardy using this API: https://jservice.io/

## Reference Implementation

https://user-images.githubusercontent.com/8116130/107770177-0752d600-6d07-11eb-9047-44bd48177975.mov

## Gherkin

GIVEN a user hasn't started playing yet
WHEN they click on elements in the user response form
THEN they should be disabled
AND the main box should prompt them to request their first clue

GIVEN a user hasn't started playing yet
WHEN they click the "next clue" button
THEN a clue should appear in the main box
AND the form elements should be enabled

GIVEN a clue is in the main box
WHEN the user submits a correct answer
THEN user should have the associated number of points added to their score
AND a new clue should appear

GIVEN a clue is in the main box
WHEN the user submits an incorrect answer
THEN the user should see an alert box containing the correct answer
AND the user should have the associated number of points subtracted from their score
AND a new clue should appear

## Directions

You can begin by forking this repl: https://repl.it/@andyweiss1982/AjaxFor200

There are more step by step instructions in the `script.js` file.

Feel free to work collaboratively or independently.

## Submission Guidelines

At 10 AM, paste a link to your repl as a comment to this issue.

**Comment by lilygdu** [comment]
https://repl.it/join/iddmmyny-lilygdu
