### ISSUE TITLE
Phone Book API

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#60]
# Objective

I have built a very basic phone book API with some fake data at https://phonebook.andyweiss1982.repl.co/.

The problem is: it returns 10,000 entries when you hit it, which means it takes _seconds_ to load and parse (the horror 😱 )!

Plus, it's unsorted and not searchable 🤕.

Your goal is to implement sorting, filtering, and pagination.

## Directions

Fork the repl at https://repl.it/@andyweiss1982/PhoneBook#index.js

There are more specific instructions as comments inside the file.

## Submission Guidelines

Paste a link to your forked repl as a comment to this issue at 10 AM EST.

**Comment by ebugbey** [comment]
https://repl.it/join/vyiakeem-ebugbey
