### ISSUE TITLE
Give it a REST

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#61]
# Objective

Let's flesh out the rest of our phone book REST API.  I have forked where we left off here: https://repl.it/@andyweiss1982/PhoneBook-REST.  Feel free to re-fork it to work on your own account.

Below are detailed specs for how we want the API to work.  Try to implement them as faithfully as possible, they are listed in priority order.

---

### The API should support DELETE requests

**GIVEN** a DELETE request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**THEN** the contact should be removed
**AND** the API should respond with a status code of 200
**AND** a JSON representation of the contact that was just deleted

### The API should support single attribute PATCH requests

**GIVEN** a PATCH request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ "firstName": "Tim" }`
**THEN** the contact in question should have its first name property updated to Tim
**AND** the API should respond with a status code of 200
**AND** a JSON representation of the updated contact

### The API should support multiple attribute PATCH requests

**GIVEN** a PATCH request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ "firstName": "Tim", "lastName": "Horton", "phone":  "123-456-7890"  }`
**THEN** the contact in question should have its first name property updated to Tim
**AND** its last name updated to Horton
**AND** its phone number updated to 123-456-7890
**AND** the API should respond with a status code of 200
**AND** a JSON representation of the updated contact

### The API should maintain sort order when last names change

**GIVEN** a PATCH request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ "lastName": "Horton" }`
**AND** subsequent GET request to /contacts
**THEN** the contacts should still be sorted alphabetically by last name

### The API should return meaningful errors when a contact is not found

**GIVEN** a PATCH or DELETE request to `/contacts/abc123`
**AND** no contact with the id of `abc123`
**THEN** the API should respond with a status code of 404
**AND** an error message that explains there is no such contact

### The API should return a meaningful error when the phone number is malformed

**GIVEN** a PATCH or DELETE request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ "phone":  "not-a-phone-number"  }`
**THEN** no changes to the data should be made 
**AND** the API should respond with a status code of 400
**AND** an error message that explains the required phone number format is ddd-ddd-dddd

## The API should return a meaningful error when unexpected attributes occur in the request body

**GIVEN** a PATCH request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ "hello":  "hi", "lastName": "Horton" }`
**THEN** no changes to the data should be made
**AND** the API should respond with a status code of 400
**AND** an error message that explains only firstName, lastName, and/or phone are allowed

## The API should return a meaningful error when unexpected attributes occur in the request body

**GIVEN** a PATCH request to `/contacts/abc123`
**AND** a contact with the id of `abc123`
**AND** a request body of `{ }`
**THEN** no changes to the data should be made
**AND** the API should respond with a status code of 400
**AND** an error message that explains at least one of firstName, lastName, and/or phone is required

---

## Dev Notes

You may find some of the following methods useful:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

## Submission Guidelines

At 10 AM, paste a link to your updated repl as a comment to this issue

**Comment by ebugbey** [comment]
https://repl.it/join/vvhnyqoo-ebugbey
