### ISSUE TITLE
50 Impossible Whoppers

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#68]
# Objective

This morning's activity is a recap of how we have historically created interactions in this course, with a little gratuitous animation thrown in:

### Our steps

1. Query elements from the DOM that will accept interaction or respond to interaction
2. Write functions that define the changes you want to make to the DOM in response to a given event
3. Add event listeners to elements to ensure the functions run when the user performs the desired action

Your goal is to take this starter repl: https://repl.it/@andyweiss1982/50-Impossible-Whoppers, and give it the following functionality.

https://user-images.githubusercontent.com/8116130/109450129-2e541c00-7a18-11eb-93e7-67b214e156a4.mov

Don't worry, all of the HTML and CSS is pre-written for you, so you can focus on just the JS.  But take a close look at the HTML and CSS so you can understand how to make the interaction behave as desired.

## Spec

GIVEN a user is on the page
WHEN they click any impossible whopper
THEN the whopper should spin out from the screen
AND ultimately disappear
AND the counter at the top of the screen should decrement by 1

GIVEN a user is on the page
WHEN they click the first impossible whopper
THEN the footer should slide into view

GIVEN a user is on the page
WHEN they click the last impossible whopper
THEN the footer should slide over the entire screen
AND the message should change to "mission accomplished"

## Dev Notes

* You will likely need to target the header, footer, counter, and message with `querySelector`, and all of the whoppers with `querySelectorAll`: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll
* You can tell _which_ whopper was clicked by using the `event.currentTarget` property: https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
* You already have classes to trigger the `.spinout` and put a whopper into an `.eaten` state.
* You _may_ find the `:not` selector helpful for counting the whoppers that have not yet been eat, but there is more than one way to accomplish this: https://developer.mozilla.org/en-US/docs/Web/CSS/:not
* You need to time the whopper to disappear just as the animation ends.  You can do this with a `setTimeout` (https://www.w3schools.com/jsref/met_win_settimeout.asp) or with the `animationend` event listener:  https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationend_event

## Submission Guidelines

Paste a link to your forked repl as a comment to this issue at 10 AM EST

**Comment by lilygdu** [comment]
https://repl.it/join/bsyqqfap-ebugbey
