### ISSUE TITLE
Make an Issue of It

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#74]
# Objective

This morning's exercise doesn't involve writing _any_ code.  Instead, I want you to focus on writing a really solid issue that describes what needs to happen with our sign up form's validations.

## Directions

Write some Gherkin acceptance criteria that manages to encompass all of the following complexity (and potentially anything else I might have missed?):

* There are 4 different _types_ of fields in our form (select, text input, email input, checkbox).
* Some of them are _required_ others are _optional_
* The fields all behave differently, based on whether or not the form has already been submitted
* Some of them have multiple reasons they could potentially be invalid (hello, email?)
* Some of them _need_ to interact with the server _before_ we can know if they are valid (does this account already exist?)
* Some of them can show in _default_, _valid_ or _invalid_ states, others only show an _error_ or _default_ state, others just show a _default_ state.

Then, add some User Stories that explain the use cases for these acceptance criteria.

Finally, include screenshots that demonstrate how the form should look in the various possible scenarios.

## Submission Guidelines

Post a link to your issue as a comment to this issue at 10 AM....  

## What's Next?

I already wrote some code that I _think_ will meet the correct acceptance criteria, but we will compare your criteria against my code and see if we land in the same place, or if one of us has missed an important edge case!

**Comment by lilygdu** [comment]
https://github.com/rbi-learning/daily-exercises/issues/75
