### ISSUE TITLE
Sweat the Details

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#81]
# Sweat the Details

## Submission Guidelines

- Fork the repl at https://replit.com/@andyweiss1982/SweatTheDetails
- Paste the url of your forked repl as a comment to this issue

## Objective

Build a clone of the "Top Questions" section at https://www.popeyes.com/frequently-asked-questions

## Example

![ezgif com-gif-maker (23)](https://user-images.githubusercontent.com/8116130/119660297-187aab00-bdfd-11eb-85da-f10123197862.gif)

## Instructions

- Implement a `details` element with a `summary` and an `article` for each question.
- The `::marker` for the `summary` element should be a plus ➕ on the right hand side.
- Each question should be an `h3` element, but you add CSS to make sure it shows on the same line as the ➕ (see the link in the resources section).  
- The `cursor` should show a finger when you hover over the question (see the link in the resources section).
- When you hover over an individual question, or when the `details` element is `open`, the `background-color` should change.
- When the `details` element is `open`, the `h3` and `::marker` should change `color`
- Bonus points if you can rotate the ➕ when the `details` element is `open`.
- Mega bonus points if you can animate the transitions but I have zero expecation of this.

## Resources

- https://css-tricks.com/two-issues-styling-the-details-element-and-how-to-solve-them/
- https://developer.mozilla.org/en-US/docs/Web/CSS/:hover
- https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate()
- https://css-tricks.com/almanac/properties/t/transition/

## Note

A very tiny bit of CSS has already been written for you, _mostly_ to get the Popeyes custom fonts working.  You shouldn't need to change any of it.

**Comment by vlopesdacosta** [comment]
https://replit.com/join/btntnqxv-vlopesdacosta

**Comment by Latte-King** [comment]
https://replit.com/join/mrzfjyiz-rhamid2https://replit.com/join/mrzfjyiz-rhamid2
