### ISSUE TITLE
Weather Bar

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#82]
# Objective

Add a Navbar (or 3) to your weather sites: 

- https://replit.com/join/ashmnouq-vlopesdacosta
- https://replit.com/@rhamid2/weather-day-1#index.html <- Reyaz please send the "join" link when you can 😀

## Example

![Screen Shot 2021-05-27 at 7 59 39 AM](https://user-images.githubusercontent.com/8116130/119822358-90120e00-bec1-11eb-941b-d6f90503460a.png)

https://weather.com/weather/tenday/l/a046396ee1fec5cda57bcb108802d744193aaf1826d24362b54fd32d5f2393ec

## Instructions

1. Add a `header` element above your site's `main`.  This header actually doesn't need to have fixed position if you visit weather.com.
2. Add three `nav` elements inside your `header`, one for each row of the navbar.  Give each one a dedicated `height` and `background-color`.  If you see empty space around the `header`, you can probably eliminate it by declaring a `margin` of `0` on the `body` element.
3.  Work your way from the bottom `nav` element up.  Each bar can likely be implemented with some combination of `flex` and `grid` displays, `ul`, `li` and `a` elements with `padding`, `margin` and `border`.  
4. Don't worry about the search bar or making the navbar responsive with media queries, _yet_ 🤓
4. You can continue to use the images in #80, or copy `svg` elements from the actual weather.com site.

## Submission Guidelines

Feel free to work together but please continue to write code on your individual repls.  No need to resubmit them since I already have the urls.

**Comment by vlopesdacosta** [comment]
https://replit.com/@vlopesdacosta/WeatherWebsite#style.css

**Comment by Latte-King** [comment]
https://replit.com/join/uwamyyht-rhamid2
