### ISSUE TITLE
Donuts and Media Queries

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#83]
# Objective

Implement this card from the Tim Horton's homepage using responsive media queries:

##### On Large Screens
![Screen Shot 2021-05-28 at 8 38 03 AM](https://user-images.githubusercontent.com/8116130/119985142-4512fc00-bf90-11eb-917e-cb1b189cef2b.png)

##### On Small Screens
![Screen Shot 2021-05-28 at 8 38 22 AM](https://user-images.githubusercontent.com/8116130/119985174-522feb00-bf90-11eb-9921-adc0c507d317.png)

## Submission Guidelines

- Fork the repl at https://replit.com/@andyweiss1982/tims-starter
- Fonts and colors have been set up for you, and images are in the `images` folder
- Paste a *join* link to your repl as a comment to this issue at 10 AM EST

## Instructions

- Use `display: flex;` for laying out items.
- On large screens, you can give each child element a width of 33% to keep things evenly spaced
- At different sizes, you can change the `flex-direction` from `row`, to `column`, or even `row-reverse`!

## Resources

- https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction

**Comment by Latte-King** [comment]
https://replit.com/join/ilfihkrk-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/jowrroic-vlopesdacosta
