### ISSUE TITLE
Burger Chasers

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#84]
# Objective

Write the JavaScript that will implement the gameplay in the example below:

https://user-images.githubusercontent.com/8116130/120318032-52402b80-c2ad-11eb-8102-48aa5a1cc232.mov

## Acceptance Criteria

_GIVEN_ a burger visible on the screen
_WHEN_ a user clicks on it
_THEN_ is should disappear
_AND_ the number of points should increment by 1

_GIVEN_ the time remaining is visible on the screen
_WHEN_ a second elapses
_THEN_ it should decrement by 1
_AND WHEN_ it reaches 0
_THEN_ the timer should read "Game Over"
_AND_ all of the burgers should disappear

## Instructions

Fork the repl at: https://replit.com/@andyweiss1982/BurgerChasers

Start by taking a close look at the HTML and CSS that you have been given as a starter.  You are welcome to change them if you want to, but everything you _need_ to make the game work is already there, namely:

1. 100 divs with a class of `.burger`
2. Elements with an id of `#game`, `#timer`, `#time-remaining`, and `#points`
3. CSS that specifies how a `.burger` should display when it get's the class `.eaten` or is inside of a `#game.over` element.

## Dev Notes

1. Query the DOM for `#game`, `#points`, `#timer` and `#time-remaining` using `document.querySelector` and store each value in a `const`
2. Query the DOM for all of the `.burger` divs with `document.querySelectorAll` and store the list of all burgers in a `const`
3. Loop over each `.burger`, and add an event listener so that when a burger is clicked, you add a class of `.eaten` to it, and increment the `textContent` of the `#points` span by 1
4. Set an interval to run every 1000 milliseconds, that decrements the `textContent` of `#time-remaining` by 1.
5. Once `#time-remaining` gets to 0, change the `textContent` of the `#timer` to "Game Over" and add a class of `.over` to the `#game` element.

## Resources

- https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
- https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
- https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
- https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
- https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval

**Comment by Latte-King** [comment]
https://replit.com/join/fmarfrbk-rhamid2
