### ISSUE TITLE
I'd Rather Be Watching Movies

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#87]
# Objective

Build a movie search website that uses the OMDB API: https://www.omdbapi.com/apikey.aspx

## Instructions

There are detailed instructions for you in the `script.js` file of this starter repl: https://replit.com/@andyweiss1982/IdRatherBeWatchingMovies-1#script.js

### Gotchas

**Please fork the repl before doing any work!**

**Don't forget to click the link in your activation email once you sign up for an API key!**

**Make sure you make your API requests to an `https` url, not `http`!**

Remember, every API is a little different.  So you can learn many things and gain insight from looking at code samples from yesterday's exercise, but you will be disappointed if you just try to copy and paste yesterday's code and change a few things.

Just a few examples: The search parameters are different, there's no "next" url, the results come back in a "Search" array, etc.  

## Example

![Screen Shot 2021-06-04 at 8 41 48 AM](https://user-images.githubusercontent.com/8116130/120802685-ba427c00-c510-11eb-841b-4b11e2e32c72.png)

## Submission guidelines:

Paste a link to your forked repl as a comment to this issue at 10 AM EST

**Comment by Latte-King** [comment]
https://replit.com/join/lihbznwg-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/obwkeglh-vlopesdacosta
