### ISSUE TITLE
You Got Jokes?

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#89]
# Objective

Build a random joke generator

## Example

![Screen Shot 2021-06-08 at 8 23 55 AM](https://user-images.githubusercontent.com/8116130/121184258-e91f6180-c832-11eb-9722-a86ba9cd98bf.png)

## Acceptance Criteria

GIVEN a visible setup for a joke
WHEN the user clicks on the setup
THEN the punchline should become visible

GIVEN a visible punchline for a joke
WHEN the user clicks the setup
THEN the punchline should not be visible

GIVEN a next joke button and a visible joke
WHEN the user clicks it
THEN the punchline should hide
AND the setup and punchline should be replaced with a new joke

## Instructions

1. Fork the repl at https://replit.com/@andyweiss1982/JokesAPI
2. follow the instructions in `script.js`

## Submission Guidelines

Paste a link to your forked repl at 10 AM EST

**Comment by Latte-King** [comment]
https://replit.com/join/vfsauoligp-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/trowkbetmo-vlopesdacosta
