### ISSUE TITLE
BK Array Cardio

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#90]
# Objective

Help us find important data from the list of BK Restaurants in the USA.

# Instructions

1. Fork the repl at https://replit.com/@andyweiss1982/BK-Array-Cardio-1
2. Focus on the `index.js` file -- you can safely ignore the top line or two.  They pull data from sanity and store it in a const called `allRestaurants`.  We will learn more about that today but that's really all you have to know for now.
3. Hint: You can always `console.log(allRestaurants)` if you need to see how the data is structured!
4. Look at the example in `index.js`
5. Use it to fill in the blanks for the 3 questions listed

## Submission Guidelines

- You may work together but please submit independently
- Paste a link to your forked repl as a comment to this issue at 10 AM EST

**Comment by Latte-King** [comment]
https://replit.com/join/tgwhhfiwjo-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/xaalokqhvy-vlopesdacosta
