### ISSUE TITLE
2 Truths and a Lie

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#91]
# Objective

We are going to play 2 Truths and a Lie using SQL.

If you are unfamiliar with the game, here is the basic idea: https://www.thoughtco.com/2-truths-lie-idea-list-1-31144

## Instructions

1. Accept your invite to Elephant SQL

![Screen Shot 2021-06-10 at 7 38 50 AM](https://user-images.githubusercontent.com/8116130/121518816-e94c6800-c9be-11eb-9870-57f8965d7d64.png)

2. Navigate to the "Shared Demo" database

![Screen Shot 2021-06-10 at 7 19 34 AM](https://user-images.githubusercontent.com/8116130/121518950-11d46200-c9bf-11eb-9c2e-85772a780f9c.png)

3. Click on "Browser" to access a SQL terminal

![Screen Shot 2021-06-10 at 7 20 04 AM](https://user-images.githubusercontent.com/8116130/121518997-287ab900-c9bf-11eb-819d-71bc4c84c829.png)

4. Take a look at the following query I used to set up 2 tables: one for "people" and one for "assertions".  **YOU SHOULD NOT EXECUTE THIS QUERY, I AM JUST SHOWING IT SO YOU UNDERSTAND THE TABLE STRUCTURE.** Take a moment to google any SQL concepts you are unfamiliar with.

![Screen Shot 2021-06-10 at 7 32 33 AM](https://user-images.githubusercontent.com/8116130/121519849-31b85580-c9c0-11eb-9892-b23151525870.png)

5. Now, execute a query that will create a person representing you in the database.  **TAKE NOTE OF YOUR ID, IT WILL BE SOMETHING OTHER THAN 1 AND YOU WILL NEED IT IN SUBSEQUENT STEPS**

![Screen Shot 2021-06-10 at 7 33 30 AM](https://user-images.githubusercontent.com/8116130/121520021-675d3e80-c9c0-11eb-9367-d61a55213e9f.png)

6. Now, insert three "assertions" about you.  Two should be true, and 1 should be a lie, but don't tell us which is which yet.  If you look up at the table definitions, you will see that the default 'status' is 'unknown', which is what we want for now.  **MAKE SURE YOU USE YOUR OWN PERSON_ID, NOT THE NUMBER 1 (WHICH IS MINE!)**

![Screen Shot 2021-06-10 at 7 35 58 AM](https://user-images.githubusercontent.com/8116130/121520175-9ffd1800-c9c0-11eb-9cdf-1779318fa1e8.png)

![Screen Shot 2021-06-10 at 7 36 32 AM](https://user-images.githubusercontent.com/8116130/121520201-a7242600-c9c0-11eb-82c9-049644b4727a.png)

![Screen Shot 2021-06-10 at 7 37 23 AM](https://user-images.githubusercontent.com/8116130/121520230-af7c6100-c9c0-11eb-92de-74df994f52dc.png)

7. Finally, make sure your data is correct by querying for your own assertions based on your name:

![Screen Shot 2021-06-10 at 7 44 22 AM](https://user-images.githubusercontent.com/8116130/121520481-f407fc80-c9c0-11eb-93ea-28b15de2fdc3.png)

## Submission Guidelines

Paste a screenshot of your query from number 7, and its results, as a comment to this issue.

**Comment by Latte-King** [comment]
![image](https://user-images.githubusercontent.com/73479485/121529650-9e385200-c9ca-11eb-99ae-5e330d326864.png)

**Comment by vlopesdacosta** [comment]
![image](https://user-images.githubusercontent.com/73478284/121532877-24a66100-c9d6-11eb-9619-12233f7048fa.png)
