### ISSUE TITLE
Donut of the Day API

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#92]
# Objective

Build an API that will allow users to vote for their favorite Tim Hortons donut, once a day.

## Example

Eventually we will be building an app like this: https://vote-daily-donut.herokuapp.com/

## Instructions

- Fork the repl at https://replit.com/@andyweiss1982/DonutVotes
- There are more detailed instructions in `index.js`

### It should record new votes

GIVEN a POST request to the `/votes` endpoint
WHEN the request body is `{ "donut_id": "donut_123", "voter_id": "voter_987" }`
AND voter_1235643 has not yet voted today
THEN the vote should be marked with the current date and assigned a unique id in the data store
AND the API should respond with a 200 status code
AND a JSON representation of the recorded vote

```
{
	"id": 4,
	"donut_id": "donut_123",
	"voter_id": "voter_987,
	"date": "2021-02-23"
}
```

### It should overwrite existing votes for the current date

GIVEN a POST request to the `/votes` endpoint
WHEN the request body is `{ "donut_id": "donut_123", "voter_id": "voter_987" }`
AND voter_987 has already voted today
THEN the voter's previous vote should be replaced with the incoming vote in the data store
AND the API should respond with a 200 status code
AND a JSON representation of the recorded vote

### It should show all votes for the current day

GIVEN a GET request to the `/votes` endpoint,
WHEN three people have voted already today
THEN the API should respond with a 200 status code and a JSON representation of the anonymous vote tally:

```
{
  "donut_123": 1,
  "donut_456": 2,
}
```

### It should persist votes in a database

GIVEN a recorded list of votes
WHEN there is a temporary server outage
AND the server is restarted
THEN the votes should still persist

**Comment by Latte-King** [comment]
https://replit.com/join/iqdiogorzi-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/vxfdkhnjxp-vlopesdacosta
