### ISSUE TITLE
Email JS

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#93]
# Objective

Have our Tim Hortons application send a (for now, fake) one-time password to the user when they complete the login form.

## Reference Implementation

1. Visit https://www.timhortons.com/signin
2. Enter your email address (assuming you already have an account)
3. You should receive an email that looks like this:

<img width="1105" alt="Screen Shot 2021-06-14 at 8 06 40 AM" src="https://user-images.githubusercontent.com/8116130/121889633-7ce7a680-cce7-11eb-8f9e-f14cc125b707.png">

## Email JS Starter

We are going to use a service called EmailJS to make this work: https://www.emailjs.com/ Don't worry about setting up an account there, we can use mine for now.  I set up a "default template" by literally copying and pasting the email above into their system and making a few small tweaks:

![Screen Shot 2021-06-14 at 8 12 00 AM](https://user-images.githubusercontent.com/8116130/121890421-52e2b400-cce8-11eb-80ae-77933131c231.png)

Notice there are placeholders for `{{code}}`, `{{to_email}}`, and `{{current_date}}`.

Also notice the "playground" link in the upper right hand corner of the picture.  It takes you here: https://jsfiddle.net/sdycme7w/.  

Visit that url now.  You will see a form with `code`, `to_email`, and `current_date` fields. 

![Screen Shot 2021-06-14 at 8 15 33 AM](https://user-images.githubusercontent.com/8116130/121890768-b4a31e00-cce8-11eb-87c4-874f361255a8.png)

Enter any random 6-digit code into `code`, your email into `to_email`, and "2021-06-14" into `current_date`, then submit the form.  You should receive a really close reproduction of the actual Tim Hortons one-time password email!

**Now you need to figure out how to shoehorn this functionality into our current TH clone implementation.**

## Instructions

- Start by forking https://replit.com/@andyweiss1982/tims-starter-2#login.html or working from your own existing copy.
- Looking at the playground, these two lines appear to be important for working with the `emailjs` library:

```
<script type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/emailjs-com@2/dist/email.min.js"></script>

<script type="text/javascript">
  emailjs.init('user_C0PNrF65QnYy5WbnUlyV7')
</script>
```

- Put them in the bottom of the `body` tag of the `login.html` page.
- This code from the playground looks like it works when the info comes directly from a form:

```
 const serviceID = 'default_service';
 const templateID = 'template_yx0d6ek';

 emailjs.sendForm(serviceID, templateID, this)
```

- But this workflow doesn't work for our feature -- the whole point of this feature is that the user doesn't know the password yet!
- This code looks like it will send an email programaticallly: https://www.emailjs.com/docs/sdk/send/. You will have to use the `serviceId` and `templateId above`, and pass `code`, `to_email` and `current_date` as templateParams. 
- You will probably have to add an event listener to the submit event on the form, prevent the default behavior, and then add some version of this code to a `handleFormSubmit` function.  
- You can get the `to_email` from the value of the email input.
- You can generate the `current_date` like this:  https://stackoverflow.com/questions/23593052/format-javascript-date-as-yyyy-mm-dd#answer-38148759
- And you can generate a random 6 digit code like this: https://stackoverflow.com/questions/21816595/how-to-generate-a-random-number-of-fixed-length-using-javascript#answer-21816636

## Submission guidelines

Paste a link to your repl at 10 AM.

**Comment by Latte-King** [comment]
https://replit.com/join/josqxpendr-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/ardlakxznt-vlopesdacosta
