### ISSUE TITLE
Confirm OTP

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#94]
# Objective

Allow the user to sign in by confirming the OTP in their email

## Implementation

I made a few minor changes from where you left off yesterday.  Start today's activity by forking this repl: https://replit.com/@andyweiss1982/tims-starter-3

Check out the actual implementation at timhortons.com.  Provide your email to the login form: 
![Screen Shot 2021-06-15 at 7 10 18 AM](https://user-images.githubusercontent.com/8116130/122042967-cf3ccc00-cda8-11eb-8d9d-df06907685d7.png)

and notice how the _next_ page you are redirected to _remembers_ your email!

![Screen Shot 2021-06-15 at 7 10 24 AM](https://user-images.githubusercontent.com/8116130/122043015-dc59bb00-cda8-11eb-8225-351a9642a99d.png)

This can be done with `localStorage`: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#example

In line 69 of (your fork of) https://replit.com/@andyweiss1982/tims-starter-3#javascript/signup.js, add: `localStorage.setItem('userEmail', user.email)` before you redirect the user.

Then, add a new `confirm-otp.js` file to the `javascript` folder and place a `<script src="javascript/confirm-otp.js"></script>` tag at the bottom of the body of `confirm-otp.html`.  Inside that file, you should be able to `alert(localStorage.getItem('userEmail'))` and demonstrate that you still have access to the email of the user from the previous page. 

Use this information to populate the text elements of `confirm-otp.html`.  There should be an h1 that says: "Verify with code", and an h2 that says: "We just sent an email with login instructions to **the name of the user from the last page**"

Next, add a label that says "Enter Verification Code Below:" and a text input.  The textinput should have a `maxlength` of 6 and a `pattern` of `[0-9]*`.

Add an event listener to the input event on the text input, such that you run a function called "handleInput" whenever the user interacts with the input.

Inside the `handleInput` function, if the length of the input's value is 6 characters, then you will want to make a POST request to the `/confirm-otp` endpoint of our auth api from yesterday.   You will need to send the input's value as the otp code, and the `userEmail` value  from `localStorage` as the email.  Use this postman example from yesterday as a reference:

![Screen Shot 2021-06-15 at 7 24 55 AM](https://user-images.githubusercontent.com/8116130/122044736-d9f86080-cdaa-11eb-8949-c59111b9f078.png)

You have the ability to check if a response from an API is "ok", meaning successful.  You can see an example in line 60 of https://replit.com/@andyweiss1982/tims-starter-3#javascript/signup.js

If the API response is "ok", then alert("You are now logged in"), otherwise, alert("That's not quite right").  We will work on tightening up this part of the UI later

## Submission guidelines

Paste a link to your forked repl as a comment to this issue at 10 AM

**Comment by vlopesdacosta** [comment]
https://replit.com/join/qcjgttvzoq-vlopesdacosta

**Comment by Latte-King** [comment]
https://replit.com/join/jbpcxpinwv-rhamid2
