### ISSUE TITLE
Tim Hortons Menu

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#95]
# Objective

Display the front page of the Tim Hortons menu

![Screen Shot 2021-06-16 at 6 42 08 AM](https://user-images.githubusercontent.com/8116130/122205629-7899c580-ce6e-11eb-9c22-595d8b24d3db.png)

## Instructions

- Fork the repl at https://replit.com/@andyweiss1982/tims-starter-4#index.html
- Visit https://czqk28jt.apicdn.sanity.io/v1/graphql/prod_th_us/default
- Paste the following query into the GraphQL playground:
```
query {
  Menu(id:"f2f90f07-4765-458a-b1ea-9d3c287a5ca7"){
    options {
      ... on Picker {
        _id
        name {
          en
        }
        image{
          asset {
            url
            metadata {
              lqip
            }
          }
        }
      }
      ... on Section {
        _id
        name{
          en
        }
        image{
          asset {
            url
            metadata {
              lqip
            }
          }
        }        
      }
    } 
  }
}
```

If you take a close look at the the response from the Sanity API, you should see the exact information necessary to display the Tim Hortons menu!

- Make a `menu.html` page, and paste in the `header` plus all of the common css that all pages use so far.
- Put the word `Menu` in an `h1`
- Add a `main` element
- Create a `menu.js` script and a `menu.css` stylesheet and make sure that both files are correctly referenced inside of `menu.html`. 
- Inside of `menu.js`, declare a `renderMenuItem` function that returns the markup needed to display one item on the menu.  Taking a quick look at the screen, you probably just need a `div` with an `img` and an `h2` element inside.  Don't worry about making any links work yet.  If you have extra time, you can revisit this to make the `blurup` effect work with the `lqip`.
- declare an async `fetchMenu` function that makes the above graphQL query from sanity.  Await parsing the JSON response.  It looks like the menu items you are looking for are an array under the "data" -> "Menu" -> "options" keys.
- Map over the `data.Menu.options`, rendering each one, and joining the result into a single string.  Insert this string into the innerHTML of the main element.
- Add styles to `menu.css` to make everything look as close as possible to the reference implementation.  Notice the layout changes at small screen sizes, and we have done something similar to this before at https://replit.com/@andyweiss1982/Popeyes-Grid

**Comment by Latte-King** [comment]
https://replit.com/join/yphnpbtdue-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/fzcxylxted-vlopesdacosta
