### ISSUE TITLE
useState practice

### ISSUE THREAD

**Issue by andyweiss1982** [rbi-learning/daily-exercises#99]
# Objective

Build a dog age calculator and a temperature converter using `React.useState`

## Instructions

There are two repls for you to fork this morning:

- https://replit.com/@andyweiss1982/DogAgeCalculator
- https://replit.com/@andyweiss1982/TempConverter

In each case, acceptance criteria and more step-by-step instructions have been written for you in `src/App.jsx`

## Submission Criteria

Paste links to your forked repls at 10 AM EST

## Dev Notes:

- https://reactjs.org/docs/hooks-state.html
- https://www.freecodecamp.org/news/what-every-react-developer-should-know-about-state/

**Comment by Latte-King** [comment]
https://replit.com/join/xzvhlrjdjt-rhamid2

**Comment by vlopesdacosta** [comment]
https://replit.com/join/tcynkryowt-vlopesdacosta
https://replit.com/join/qrjmbeeisp-vlopesdacosta

**Comment by Latte-King** [comment]
https://replit.com/join/mvvouxipim-rhamid2
